### ISSUE TITLE
How to setup voices if they not avaiable?

### ISSUE THREAD

**Issue by evadogstar** [leonar15/SelectNSpeak#1]
Hello, thanks for this,
How to setup voices if they not available?

**Comment by leonar15** [comment]
Thanks for the bug report. I can imagine two possibilities for what's going on.

**Possible problem 1:** The voices are not loading properly due to a bookmarklet bug
Could you try this? 
- Load the bookmarklet on any webpage. 
- Then close the bookmarklet by pressing the "x" button.
- Without reloading the webpage, re-open the bookmarklet
Do the voices show up? Also, it would be helpful if you mention which browser and operating system you're using.

**Possible problem 2:** Your OS doesn't have any available voices
The bookmarklet depends on voices come from your operating system. 

Instructions for adding voices to your OS:
- _MacOS_: https://support.apple.com/guide/mac-help/change-the-voice-your-mac-uses-to-speak-text-mchlp2290/mac
- _iOS, iPadOS_: https://support.apple.com/en-us/HT202362
- _Windows 10_: https://support.microsoft.com/en-us/office/download-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130

**Comment by leonar15** [comment]
I've added a section to the main project page, which lists how to add voices depending on your OS

**Comment by evadogstar** [comment]
It's #2. 
I'm on Fedora + Firefox
Thanks!

**Comment by leonar15** [comment]
It looks like there's a pretty good StackOverflow Question that shows how to install voices on Fedora. 

I'd take a look at this answer for more details: https://stackoverflow.com/a/48180613/2141296

**Comment by evadogstar** [comment]
Thanks!
